### PR TITLE
Update backend chapter for dune

### PR DESCRIPTION
**Pull request by mseri**
I have also added some minor edits, and removed the future plans as it seemed out of context for the book.

What about adding a simple but more complex, interactive, example using owl-ode or something else? The downside is that we will need to provide the binding to a plotting library.

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
Also, I am not sure how this can be tested for real (I have compilerd and run everything locally)

**Comment by jzstark** [comment]
Thanks for the editing! For testing the effect of change on html webpages, please run `make` and check the generated html files in `docs/` in browser, make sure no error in compiling, and also include the updated html file in the PR. 

I'm not sure about how this interactive example should look like or fit into the tooling workflow of current tutorial book. I'm thinking perhaps it would be better to build such an example somewhere else, without restriction of plotting libraries and such, and then the team could discuss if and how it should be included in the book.

**Comment by mseri** [comment]
I don't know if it is a bug in dune 2.0, I need to dig deeper. But with dune 2.0 is impossible to build due to
```
File "static/dune", line 361, characters 13-27:
361 |   (deps    %{bin:otb-build}
                   ^^^^^^^^^^^^^^
Error: Program otb-build not found in the tree or in PATH
 (context: default)
```

**Comment by mseri** [comment]
> I'm not sure about how this interactive example should look like or fit into the tooling workflow of current tutorial book. I'm thinking perhaps it would be better to build such an example somewhere else, without restriction of plotting libraries and such, and then the team could discuss if and how it should be included in the book.

I agree!

**Comment by jzstark** [comment]
Hmm, that looks like on of the previous error message. Perhaps update the docker image would help? Currently all the compiling work is done in the container and you don't even need to have OCaml installed for compiling.  Also my dune version is 2.0.1, with OCaml 4.09.0.

**Comment by mseri** [comment]
I have been working for a while to try and make this work with duniverse, the supposedly right way for rwo. This failure is a new blocker. The branches have diverged a lot, I’ll try to update them and to figure it out. Not a major problem for this PR

**Comment by jzstark** [comment]
`duniverse` is a cool tool and we also use that in some other projects, but one issue that cannot be solved is the random number as you have mentioned. Even with the same seed, the random number generated on different machines vary slightly, which leads to compiling error.  Using docker container can effectively avoid such issues.

I have tested this PR, generating the html files without compiling error. So if there is no pending fix or more review suggestions from @ryanrhymes, I would merge this PR later, and then help to update the corresponding html files. However, I strongly suggest considering using the up-to-date tooling in updating the book since using Docker avoids many software version issues and make sure that no new compiling errors are introduced.

**Comment by mseri** [comment]
I don’t want to get rid of docker, I want to enable them to stay minimal and benefit from duniverse: duniverse would ensure that we benefit from improvements in rwo, contribute to its development and that we have a fixed tracked version of the dependencies that do not depend on random changes on opam or in the containers.

**Comment by jzstark** [comment]
The current tooling has already taken days of effort of Liang, and afaik there is no long term plan to completely sync with RWO. We believe that instead of over-optimising the toolchain, adding more content should be the major concern of the book for now.

**Comment by mseri** [comment]
Fine, I can drop the effort, it’s not a problem. We had started it with the book in agreement, and in contact with the rwo people, it is not a personal effort. I’ll send a PR to get rid of the duniverse leftovers in the current master branch if you want

**Pull request merged**
